# Generated by Django 4.0.4 on 2022-04-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_description_product_size_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
