# Generated by Django 4.0.4 on 2022-05-06 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_service_alter_product_options_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name', 'brand', 'size', 'vendor')},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='service',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.vendor', verbose_name='vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.vendor', verbose_name='vendor'),
            preserve_default=False,
        ),
    ]
